### ISSUE TITLE
Parser Issue

### ISSUE THREAD

**Issue by pudsec** [trickest/safe-harbour#2]
I think you need to look at your regex parser, I'm pretty sure `agro.au.dk`, and others, isn't a vaild Australian domain name as per your [/countries/Australia/data.csv](https://github.com/trickest/safe-harbour/blob/main/countries/Australia/data.csv) dataset. Maybe as `\.au$` might help?

**Comment by mhmdiaa** [comment]
Hi @pudsec,

You were right. It was a regex typo which was fixed in an earlier version but the workflow that pushed the results to GitHub was incorrectly configured to merge (not replace) the results of each run, so even though the latest runs' results were correct, it didn't delete the incorrect results from the faulty run. We just [fixed it](https://github.com/trickest/safe-harbour/blob/main/countries/Australia/data.csv).

This also helped us catch and fix a couple of other bugs in the workflow so thank you so much!
